TravelAgency/config/routes.rb
Rails.application.routes.draw do
  resources :packages
  resources :hotels
  root :to => "welcome#show"
end

TravelAgency/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

TravelAgency/app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :packages
  has_one_attached :image


  validates :name, presence: true 
  validates :description, presence: true 
  validates :stars, presence: true 

end

TravelAgency/app/models/package.rb
class Package < ApplicationRecord
  belongs_to :hotel

end

TravelAgency/app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

TravelAgency/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

TravelAgency/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :require_login

  def index
    @hotels = Hotel.all
  end

  def new
    @hotel = Hotel.new
  end

  def show
    @hotel = Hotel.find(params[:id])
  end


  def create
    @hotel = Hotel.new(hotel_params)

    if @hotel.save
      redirect_to '/'
    else
      @errors = @hotel.errors.full_messages
      render :new
    end
  end

  private

  def hotel_params
    params.require(:hotel).permit(:name, :description, :stars, :image)
  end
end

TravelAgency/app/controllers/packages_controller.rb
class PackagesController < ApplicationController

  before_action :require_login

  def index
  end


  def new
    @package = Package.new
    @hotels = Hotel.all
  end


  def create
    @package = Package.new(package_params)

    if @package.save
      redirect_to '/'
    else
      @errors = @package.errors.full_messages
      render :new
    end
 
  end

  private

  def package_params
    params.require(:package).permit(:destination, :departure_date, :arrival_date, :hotels_id)
  end
end

TravelAgency/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

TravelAgency/app/helpers/application_helper.rb
module ApplicationHelper
end

TravelAgency/app/helpers/hotels_helper.rb
module HotelsHelper
end

TravelAgency/app/helpers/packages_helper.rb
module PackagesHelper
end

TravelAgency/app/helpers/welcome_helper.rb
module WelcomeHelper
end

TravelAgency/app/views/hotels/_form.html.erb
<% if @errors.present? %>
  <% @errors.each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_for @hotel do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>


  <div>
    <%= form.label :description%>
    <%= form.text_area :description%>
  </div>

  <div>
    <%= form.label :stars%>
    <%= form.select :stars, ['1', '2', '3', '4','5']%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

TravelAgency/app/views/hotels/index.html.erb
<h1> Hotel list </h1>

<% @hotels.each do |hotel| %>
  <h3><%= link_to truncate(hotel.name), hotel_path(hotel) %></h3>
<% end %>

TravelAgency/app/views/hotels/new.html.erb
<h1> Create hotel </h1>

<%= render partial: "form" %>

TravelAgency/app/views/hotels/show.html.erb
<h1> <%= @hotel.name %> </h1>
<h3> <%= @hotel.stars%> stars </h3>

<%= image_tag(@hotel.image) %>


<h2>Description</h2>
<p><%= @hotel.description %></p>


<div>
  <ul>
    <li><%= link_to "Back", hotels_path %></li>
    <li><%= link_to "Delete", hotel_path(@hotel), data: {
      confirm: "Are you sure?" }, method: :delete %></li>
  </ul>
</div>

TravelAgency/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelAgency</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>
    <h2><%= link_to "Home", root_path %>
    <%= yield %>
  </body>
</html>

TravelAgency/app/views/welcome/show.html.erb
<h1>Welcome to our Travel Agency</h1>

<ul>
  <li><%= link_to "Create Package", new_package_path %></li> 
  <li><%= link_to "Create Hotel", new_hotel_path %></li>

  <li><%= link_to "Search Packages", new_package_path %></li> 
  <li><%= link_to "List Hotels", hotels_path %></li>
</ul>